name: Descargar HTML de la página de BBC y Guardar en PostgreSQL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_html:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar el código fuente del repositorio
        uses: actions/checkout@v2

      - name: Descargar el código HTML de la página de BBC
        run: |
          # Usamos curl para descargar el HTML de la página de BBC
          curl https://www.bbc.com -o bbc_homepage.html

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install psycopg2

      - name: Subir HTML a PostgreSQL
        run: |
          python3 - <<EOF
          import psycopg2

          # Datos de conexión a la base de datos PostgreSQL (modifica según tu configuración)
          host = "tu_host_postgres"
          dbname = "tu_base_de_datos"
          user = "tu_usuario"
          password = "tu_contraseña"

          # Leer el contenido del archivo HTML
          with open("bbc_homepage.html", "r") as file:
              html_content = file.read()

          try:
              # Conexión a la base de datos PostgreSQL
              conn = psycopg2.connect(
                  host=host,
                  dbname=dbname,
                  user=user,
                  password=password
              )
              cursor = conn.cursor()

              # Insertar el HTML en la base de datos
              insert_query = "INSERT INTO bbc_html (html_content) VALUES (%s)"
              cursor.execute(insert_query, (html_content,))

              # Confirmar la transacción
              conn.commit()

              # Cerrar la conexión
              cursor.close()
              conn.close()

              print("HTML guardado en la base de datos con éxito.")

          except Exception as e:
              print(f"Error al conectar o insertar datos: {e}")
          EOF
