name: Ejecutar pruebas de Python

on:
  push:
    branches:
      - main  # Se ejecuta cuando se hace push en la rama principal
  pull_request:
    branches:
      - main  # También se ejecuta cuando se crea un pull request a la rama principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar el código fuente del repositorio
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala las dependencias del proyecto

      - name: Ejecutar pruebas con pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Ejecuta las pruebas de pytest
